### PR TITLE
Update Util.java

### PR DESCRIPTION
**Pull request by alanmehio**
see 
https://github.com/Mastercard/oauth1-signer-java/issues/43

### PR checklist

- [ ] An issue/feature request has been created for this PR
- [ ] Pull Request title clearly describes the work in the pull request and the Pull Request description provides details about how to validate the work. Missing information here may result in a delayed response.
- [ ] File the PR against the `master` branch
- [ ] The code in this PR is covered by unit tests

#### Description
A clear and concise description of what is this PR for and any additional info might be useful for reviewing it.

### CODE REVIEW

**Comment by alanmehio** [comment]
[see issue]( https://github.com/Mastercard/oauth1-signer-java/issues/43)

**Comment by karen-avetisyan-mc** [comment]
Unit tests are failing for this PR.
They need to be fixed, before we can proceed.

Thanks

**Comment by alanmehio** [comment]
In the process of doing that. (Action Pending)

**Comment by alanmehio** [comment]
Closing PR and starting again

**Pull request closed without merging**
